name: Android CI

on:
  push:
    branches: [ "release", "develop" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
    - uses: actions/checkout@v4

    - name: Extract versionName from build.gradle
      id: get_version
      run: |
        VERSION=$(grep -oP 'versionName\s+"\K[^"]+' app/build.gradle)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Decode Keystore
      run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 -d > app/verba.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}.${{ github.run_number }}
        name: ${{ github.ref_name == 'develop' && 'Dev Build' || 'Release' }} ${{ steps.get_version.outputs.version }}.${{ github.run_number }}
        draft: ${{ github.ref_name == 'develop' }}
        prerelease: ${{ github.ref_name == 'develop' }}
        files: app/build/outputs/apk/release/app-release.apk
